security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        authorizationProvider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: authorizationProvider
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\AuthorizationModuleLogin

            logout:
                path:   app_logout

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: '^/provide/token', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/', roles: ROLE_USER }
