version: "3.3"

services:
    mintos-test-task:
        hostname: mintos-test-task.local.net
        container_name: mintos-test-task
        image: docker.pkg.github.com/neznajki/docker-php73/apache:latest
        volumes:
            - .:/www/default:cached
            - $HOME/.composer:$HOME/.composer:cached
            - $HOME/.cache/:$HOME/.cache:cached
            - /opt/phpstorm-coverage/:/opt/phpstorm-coverage/:cached
            - /tmp/upload:/tmp/upload:cached
        ports:
            - 80
        dns:
            - 8.8.8.8
            - 10.252.252.252
        environment:
            - VIRTUAL_HOST=mintos-test-task.local.net
            - HTTPS_METHOD=noredirect
            - APACHE_DOCUMENT_ROOT=/www/default/public/
            - API_SALT=something_random_here
            - HOME=$HOME

networks:
    default:
        external:
            name: local.net
